add notification hook
pachka-and-tochka/flappy-bird pull request #12
Opened 2022-12-21 15:38 UTC by alexmkk

### Какую задачу решаем
Добавлена Hook уведомлений и нотификация при работе с формами

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-22 11:57 UTC, dubletab approved these changes

2022-12-23 13:42 UTC, EzhikTT requested changes

2022-12-23 13:42 UTC, EzhikTT commented on packages/client/src/components/forms/ProfileForm/ProfileInfoForm/ProfileInfoForm.tsx
> +import { useNotification } from "../../../../hooks/useNorification";
А почему не через `@`?

2022-12-24 06:59 UTC, alexmkk commented on packages/client/src/components/forms/ProfileForm/ProfileInfoForm/ProfileInfoForm.tsx
> +import { useNotification } from "../../../../hooks/useNorification";
добавлено для текущих файлов, для остальных постепенно так же добавим

2022-12-26 06:50 UTC, EzhikTT approved these changes
Все ок

2022-12-26 06:59 UTC, merged