Feature/pando-40/OAuth
pachka-and-tochka/flappy-bird pull request #14
Opened 2023-01-09 12:53 UTC by Elvehnn

### Подключение Яндекс OAuth 
![image](https://user-images.githubusercontent.com/70837634/211312505-0c1ffe7f-e4c7-4c2b-aff6-24105c1cb366.png)

2023-01-10 07:10 UTC, alexmkk commented on packages/client/src/components/forms/LoginForm/LoginForm.tsx
> +} from "../../../services/authorization";
импорт через @ можно уже делать

2023-01-10 07:10 UTC, alexmkk commented on packages/client/src/components/navigation/Navigation.tsx
> +import { signout } from "../../services/authorization";
и тут

2023-01-10 07:10 UTC, alexmkk commented on packages/client/src/containers/MainLayout/MainLayout.tsx
> +import { Nullable, UserFromServer } from "../../api/typesApi";
и везде)

2023-01-10 09:14 UTC, Elvehnn commented on packages/client/src/components/forms/LoginForm/LoginForm.tsx
> +} from "../../../services/authorization";
Ща поправим!

2023-01-10 10:28 UTC, alexmkk approved these changes

2023-01-10 14:22 UTC, EzhikTT requested changes
Ответить на вопрос и импорты привести к единому виду

2023-01-10 14:22 UTC, EzhikTT commented on packages/client/src/components/forms/LoginForm/LoginForm.tsx
> +} from "../../../services/authorization";
+1

2023-01-10 14:22 UTC, EzhikTT commented on packages/client/src/App.tsx
> +                .then(async () => {
Почему здесь промисы, а в остальных местах async/await? Можно было обернуть или вынести в функцию, чтобы был единый внешний вид

2023-01-10 14:53 UTC, Elvehnn commented on packages/client/src/App.tsx
> +                .then(async () => {
Привет! поправила.

2023-01-10 14:55 UTC, Elvehnn commented on packages/client/src/App.tsx
> +                .then(async () => {
Пути еще раньше были исправлены. Странно, последние коммиты не видны что ли?

2023-01-12 08:12 UTC, EzhikTT approved these changes
Все ок

2023-01-13 10:46 UTC, merged