Feature/pando-59/add redux store
pachka-and-tochka/flappy-bird pull request #15
Opened 2023-01-10 10:42 UTC by Elvehnn

### Добавить Redux хранилище (PANDO-59)

Добавлен store и userSlice

2023-01-12 08:13 UTC, EzhikTT commented on packages/client/src/api/axiosSetup.ts
> +        // TODO: add notification
А почему туду после ретурна?)

2023-01-12 08:15 UTC, EzhikTT commented on yarn.lock
>    dependencies:
Лок можно выпилить, он не обязательный

2023-01-12 08:16 UTC, EzhikTT requested changes

2023-01-12 08:16 UTC, EzhikTT commented on packages/client/src/store/slices/user/userSlice.ts
> +import { Nullable, UserFromServer } from "../../../api/typesApi";
Снова некрасивые импорты(

2023-01-13 11:56 UTC, Elvehnn commented on packages/client/src/api/axiosSetup.ts
> +        // TODO: add notification
Привет) убежал...

2023-01-13 11:57 UTC, Elvehnn commented on yarn.lock
>    dependencies:
Done

2023-01-13 11:57 UTC, Elvehnn commented on packages/client/src/store/slices/user/userSlice.ts
> +import { Nullable, UserFromServer } from "../../../api/typesApi";
Виновата, проглядела. Done

2023-01-15 11:43 UTC, EzhikTT approved these changes
все ок)

2023-01-15 12:47 UTC, merged