Feature/pando 37-38-39
pachka-and-tochka/flappy-bird pull request #17
Opened 2023-01-18 19:50 UTC by Elvehnn

### Собран прототип SSR + Express. Подружились Redux, router, ANT Design и SSR.

Сервер запускается на loaclhost:5000. Для запуска сервера в dev mode с hmr перейдите в директорию packages/server и запустите команду yarn dev. 

![image](https://user-images.githubusercontent.com/70837634/213279298-f5e7197a-4df5-401f-b803-9a99efb48cc0.png)

2023-01-20 12:00 UTC, dubletab approved these changes

2023-01-20 12:01 UTC, off-art approved these changes

2023-01-23 09:57 UTC, EzhikTT requested changes
Общий вопрос про закоменченный код, который не помечен `TODO`  и есть в истории гита, надо бы исправить

2023-01-23 09:57 UTC, EzhikTT commented on packages/client/src/components/forms/SignUpForm/SignUpForm.tsx
> +                    // rules={[
Почему просто не удалить код? Он жеж под гитом все равно

2023-01-23 09:57 UTC, EzhikTT commented on packages/client/src/api/Auth.ts
> +        `oauth/yandex/service-id?redirect_uri=http%3A%2F%2Flocalhost%3A5000`,
`redirect_url` не нужно динамически вычислять? Или хотя бы на основе переменной окружения?

2023-01-23 09:57 UTC, EzhikTT commented on packages/client/src/App.tsx
> +    // useEffect(() => {
Этот закоменченный код нужен в репозитории?

2023-01-24 13:39 UTC, Elvehnn commented on packages/client/src/components/forms/SignUpForm/SignUpForm.tsx
> +                    // rules={[
Поправила

2023-01-24 13:42 UTC, Elvehnn commented on packages/client/src/api/Auth.ts
> +        `oauth/yandex/service-id?redirect_uri=http%3A%2F%2Flocalhost%3A5000`,
Не обязательно. Посоветовалась с другими командами - все в константы зашили. 
Насчет переменной согласна, вынесла все эндпойнты в константы, добавила зависимость от SERVER_PORT и поменяла порт в .env.

2023-01-24 13:42 UTC, Elvehnn commented on packages/client/src/App.tsx
> +    // useEffect(() => {
Уже нет)

2023-01-26 08:21 UTC, EzhikTT approved these changes
Все ок

2023-01-26 09:52 UTC, merged