add thunk
pachka-and-tochka/flappy-bird pull request #21
Opened 2023-01-30 08:56 UTC by alexmkk

### Какую задачу решаем
добавлен middleware

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-30 09:56 UTC, EzhikTT requested changes

2023-01-30 09:56 UTC, EzhikTT commented on packages/client/src/components/forms/ProfileForm/validation.ts
> +    (type: ValidatorTypes) => (input: any, value: StoreValue) =>
Писал в другом ПРе уже - почему тип изменился?

2023-01-30 09:58 UTC, alexmkk commented on packages/client/src/components/forms/ProfileForm/validation.ts
> +    (type: ValidatorTypes) => (input: any, value: StoreValue) =>
не получилось подобрать правильный тип. данные, которые приходят с поля формы не соответствуют тому формату, который ждет RuleObject.
может подскажешь как тут должно быть?

2023-01-30 10:24 UTC, dubletab approved these changes

2023-01-31 15:32 UTC, alexmkk commented on packages/client/src/components/forms/ProfileForm/validation.ts
> +    (type: ValidatorTypes) => (input: any, value: StoreValue) =>
@EzhikTT или так заливаем?

2023-02-01 14:14 UTC, merged