Feature/pando 67
pachka-and-tochka/flappy-bird pull request #23
Opened 2023-02-02 01:15 UTC by Spolete

### Какую задачу решаем
Создан пользовательский интерфейс форума. Интегрировано взаимодействие с бэкендом. Реализован функционал по созданию тем и добавлению комментариев в них.

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/88541391/216206765-2c49e2e5-3bea-4db3-b394-1a619f7d1982.mp4

### TBD (если есть)

2023-02-02 07:17 UTC, alexmkk commented on packages/client/src/store/slices/forum/forumSlice.ts
> +export const leaderboardSlice = createSlice({
forumSlice?

2023-02-02 07:35 UTC, Spolete commented on packages/client/src/store/slices/forum/forumSlice.ts
> +export const leaderboardSlice = createSlice({
Ага)

2023-02-03 08:01 UTC, EzhikTT requested changes

2023-02-03 08:01 UTC, EzhikTT commented on packages/client/src/pages/ForumPage/pages/MainThemePage/constants.ts
> +export const MAIN_THEMES = {
Почему не сделать это `enum`?

2023-02-03 08:01 UTC, EzhikTT commented on packages/client/src/pages/ForumPage/components/ForumCardHead/ForumCardHead.tsx
> +    mainThemeId: "1" | "2" | "3";
А почему числа в строках, а не числа просто?

2023-02-13 14:21 UTC, merged

2023-02-13 14:26 UTC, dubletab commented on packages/client/src/pages/ForumPage/components/ForumCardHead/ForumCardHead.tsx
> +    mainThemeId: "1" | "2" | "3";
здесь подразумевается в дальнейшем развитии  использование uuid - строка