Bugfix/fix redirect and debuging before defense dip
pachka-and-tochka/flappy-bird pull request #29
Opened 2023-02-14 10:02 UTC by dubletab

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-14 13:04 UTC, EzhikTT requested changes

2023-02-14 13:04 UTC, EzhikTT commented on packages/server/index.ts
> +    app.use(cors());
Корсу не нужны настройки? Давать доступ корс всем - не безопасно

2023-02-14 13:04 UTC, EzhikTT commented on packages/client/src/App.tsx
> +    const [isLoaded, setIsLoaded] = React.useState<boolean>(false);
А зачем тут обращение через `React`? Не вижу других `useState`

2023-02-14 13:50 UTC, dubletab commented on packages/client/src/App.tsx
> +    const [isLoaded, setIsLoaded] = React.useState<boolean>(false);
исправил

2023-02-14 13:51 UTC, dubletab commented on packages/server/index.ts
> +    app.use(cors());
вернул как было + ниже указаны респонс параметры

2023-02-14 13:52 UTC, off-art approved these changes

2023-02-16 15:35 UTC, EzhikTT approved these changes
Все ок

2023-02-16 21:21 UTC, merged