Feature/pando 7
pachka-and-tochka/flappy-bird pull request #4
Opened 2022-12-05 09:01 UTC by dubletab

### Какую задачу решаем
Добавлена игра (механика/завершение)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-05 09:05 UTC, off-art approved these changes

2022-12-06 16:02 UTC, EzhikTT requested changes
+ комменты в других ПРах

2022-12-06 16:02 UTC, EzhikTT commented on packages/client/src/components/Game/Game.tsx
> +let groundX = 0;
А почему вся эти переменные здесь, я не вынесены в класс, например? Чтобы их было удобно использовать, объединив в единую сущность

2022-12-07 14:59 UTC, dubletab commented on packages/client/src/components/Game/Game.tsx
> +let groundX = 0;
Здесь переменные, которые изменяются в рантайме, классом будет не так удобно, были бы константы, вынесли бы

2022-12-07 15:35 UTC, off-art approved these changes

2022-12-07 20:06 UTC, EzhikTT approved these changes

2022-12-10 12:30 UTC, off-art approved these changes

2022-12-11 09:05 UTC, merged