Feat/signin page  pando 14
pachka-and-tochka/flappy-bird pull request #5
Opened 2022-12-05 13:05 UTC by Elvehnn

### PANDO-14
Добавлена страница авторизации без запроса данных о юзере.
Добавлена цветовая схема приложения.

### ![image](https://user-images.githubusercontent.com/70837634/205644358-1ce91edf-40bb-4ca1-a9e9-a596165ddf62.png)

2022-12-05 13:27 UTC, Spolete commented on packages/client/src/pages/login/LoginPage.tsx
> +const leftSectionStyle = {
Привет)
А почему именно инлайн-стили?

2022-12-05 13:28 UTC, Spolete commented on packages/client/src/api/Auth.ts
> +    return await axios.post(`${PATH.BASE}auth/signin`, {
Вроде, обсуждали, что не будем использовать axios или нет?

2022-12-05 13:29 UTC, Elvehnn commented on packages/client/src/pages/login/LoginPage.tsx
> +const leftSectionStyle = {
Привет! Чтобы перебить стили antd

2022-12-05 13:31 UTC, Elvehnn commented on packages/client/src/api/Auth.ts
> +    return await axios.post(`${PATH.BASE}auth/signin`, {
В зависимостях просто установлен axios, его и взяла. Можно и на fetch переправить)

2022-12-05 13:41 UTC, Spolete commented on packages/client/src/pages/login/LoginPage.tsx
> +const leftSectionStyle = {
Я так и предположил, но я вчера перекинул эти стили в класс и всё, вроде, работало как нужно)
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/88541391/205651256-64c48e5a-e150-4588-ad3b-2ac8196292a9.png">
<img width="1512" alt="Снимок экрана 2022-12-05 в 16 41 05" src="https://user-images.githubusercontent.com/88541391/205651363-8f5b71d0-6409-4553-bd31-7e2b3d675756.png">

2022-12-05 13:46 UTC, Elvehnn commented on packages/client/src/pages/login/LoginPage.tsx
> +const leftSectionStyle = {
Я, наверно, еще заморочилась со сменой background. Наверно. это не принципиально и кода меньше. У командира еще спрошу)

2022-12-05 18:13 UTC, alexmkk commented on packages/client/src/components/forms/LoginForm/loginFormValidationSchema.ts
> +    .required("This field can not be empty")
не столь принципиально, но может на русском подсказки сделаем?

2022-12-05 18:15 UTC, Elvehnn commented on packages/client/src/components/forms/LoginForm/loginFormValidationSchema.ts
> +    .required("This field can not be empty")
предлагаю пока оставить все на английском, потом можно сделать переключатель - локализацию

2022-12-06 16:04 UTC, EzhikTT commented on packages/client/src/api/Auth.ts
> +    return await axios.post(`${PATH.BASE}auth/signin`, {
Можно сделать свою обертку на` fetch/axios`, чтобы не составлять каждый раз путь и заголовки, если потребуется. Ну и ИМХО, я больше за `fetch`

2022-12-06 16:06 UTC, EzhikTT commented on packages/client/src/components/forms/LoginForm/loginFormValidationSchema.ts
> +    .required("This field can not be empty")
На кириллице могут быть проблемы при открытии на разных осях в разных иде, что повышает возможно косяка с кодировкой. Латинские буквы универсальней)

2022-12-06 16:08 UTC, EzhikTT requested changes
+ комменты в других ПРах

2022-12-06 16:08 UTC, EzhikTT commented on packages/client/src/pages/errorPages/ErrorBoundary.tsx
> +        // @ts-ignore
Почему здесь игнор? Пропсы никак не наследуются для компилятора?

2022-12-06 16:08 UTC, EzhikTT commented on packages/client/src/constants/validateRegExps.ts
> +export const EMAIL_CHARACTERS = /^\S+@\S+\.([A-Za-z]{2,4})$/;
Тут флаги не нужны никакие в регулярках?

2022-12-06 16:08 UTC, EzhikTT commented on packages/client/src/components/forms/LoginForm/LoginForm.tsx
> +import { useFormik } from "formik";
У вас нет ограничений на используемые пакеты?

2022-12-06 17:45 UTC, Elvehnn commented on packages/client/src/components/forms/LoginForm/LoginForm.tsx
> +import { useFormik } from "formik";
![image](https://user-images.githubusercontent.com/70837634/205984277-4fbfd172-0c83-4f23-b08e-672d43e26983.png)
вот такие есть ограничения

2022-12-06 17:47 UTC, Elvehnn commented on packages/client/src/api/Auth.ts
> +    return await axios.post(`${PATH.BASE}auth/signin`, {
> Можно сделать свою обертку на` fetch/axios`, чтобы не составлять каждый раз путь и заголовки, если потребуется. Ну и ИМХО, я больше за `fetch`

Спасибо за ревью! Обсудили с командой, решили все же axios оставить. Обертку делаю в другой ветке - [feat/authorization/PANDO-16/getUserInfo](https://github.com/pachka-and-tochka/flappy-bird/tree/feat/authorization/PANDO-16/getUserInfo) 
Как раз там конфиг пропишу для запросов и обработку ошибок от API.

2022-12-06 17:52 UTC, Elvehnn commented on packages/client/src/constants/validateRegExps.ts
> +export const EMAIL_CHARACTERS = /^\S+@\S+\.([A-Za-z]{2,4})$/;
Да вроде нет, работает без них. А есть предложения? Может, упустила что-то?

2022-12-07 20:08 UTC, EzhikTT approved these changes
Все хорошо

2022-12-07 20:33 UTC, merged