Feat/profile/pando 18 19 20 21 22
pachka-and-tochka/flappy-bird pull request #9
Opened 2022-12-10 09:46 UTC by alexmkk

### Какую задачу решаем
Добавлена страница профиля, редактирования профиля + api

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/46155717/206845456-34ba5dab-a792-4bdd-a1b0-6c7c909d17f0.png)
![image](https://user-images.githubusercontent.com/46155717/206845493-94132414-42c4-4eae-bd60-b833ad1c7501.png)
![image](https://user-images.githubusercontent.com/46155717/206845532-0ac559c2-ef73-41fc-9ef0-280cbb2ae66c.png)

### TBD (если есть)

2022-12-11 09:07 UTC, dubletab approved these changes

2022-12-12 08:15 UTC, EzhikTT commented on packages/client/src/api/AvatarApi.ts
> +        console.log("Eroor: ", err);
Опечатка

2022-12-12 08:18 UTC, EzhikTT requested changes

2022-12-12 08:18 UTC, EzhikTT commented on packages/client/src/pages/main/MainPage.tsx
> +                    {/* TODO: брать имя из стора и лучший результат из локал сторедж? */}
Мб все хранить в сторе? Можно делать копию в локал сторадж, чтобы при обновлении страницы поднимать последнее состояние

2022-12-12 08:18 UTC, EzhikTT commented on packages/client/src/components/forms/ProfileForm/ProfileInfoForm/ProfileInfoForm.tsx
> +import { updateInfo } from "../../../../services/profile";
А у вас алиасов разве нет через `@`?

2022-12-12 14:25 UTC, alexmkk commented on packages/client/src/components/forms/ProfileForm/ProfileInfoForm/ProfileInfoForm.tsx
> +import { updateInfo } from "../../../../services/profile";
пока не настраивали

2022-12-12 14:26 UTC, alexmkk commented on packages/client/src/pages/main/MainPage.tsx
> +                    {/* TODO: брать имя из стора и лучший результат из локал сторедж? */}
доработки по стору планируется реализовать в ближайших задачах

2022-12-12 15:38 UTC, alexmkk commented on packages/client/src/api/AvatarApi.ts
> +        console.log("Eroor: ", err);
справлено

2022-12-15 07:08 UTC, EzhikTT approved these changes
Окей

2022-12-15 08:24 UTC, merged